#!/bin/sh 
#This job should be redirected to idqueue
#PBS -N wave
#PBS -l select=1:ncpus=24
#PBS -l walltime=08:00:00
#PBS -l place=scatter
#PBS -l accelerator_type="None"
#PBS -S /bin/sh@sdb -V 
. /opt/modules/default/init/sh
cd $PBS_O_WORKDIR
aprun -j 1 -n 1 -N 1 ./build/standing_wave
